### ISSUE TITLE
/sr join kills you when you're in a different world

### ISSUE THREAD

**Issue by SalmonGER** [GMNetwork/SpeedRun#1]
Teleports you into a void like thing

**Comment by Aericio** [comment]
cri cri

**Comment by SalmonGER** [comment]
@Aericio Perhaps location is buggy. Will check it later

**Comment by Aericio** [comment]
https://github.com/GMNetwork/SpeedRun/blob/master/resources/config.yml#L8
maybe that needs World: too?
