### ISSUE TITLE
Theoretically a bug

### ISSUE THREAD

**Issue by SalmonGER** [GMNetwork/SpeedRun#5]
https://github.com/GMNetwork/SpeedRun/blob/master/src/LittleBigMC/SpeedRun/Main.php#L66
Won't work because we deleted the "log"
solution could be a external file which gets deleted onEnable and onDisable to prevent spammy config

**Comment by Aericio** [comment]
Sounds good

**Comment by SalmonGER** [comment]
https://github.com/GMNetwork/SpeedRun/commit/8651d438101f41e6a44e6b0a7ce5effc21103692#diff-fd64f9b51a8b67a71a51bc36f67bb9d6L66

**Comment by Aericio** [comment]
What if you remove that?

**Comment by SalmonGER** [comment]
When you remove that is hould not save the players into the config anymore
